import { Link, useParams } from 'react-router-dom'
import { useState } from 'react'
import { eventRepository } from '../data/repository'
import { formatDateTime } from '../components/EventCard'
import { useApp } from '../context/AppContext'

export function EventDetailPage() {
  const { id } = useParams(); const event = eventRepository.getById(id ?? ''); const { registeredIds, register, unregister, reminders, toggleReminder } = useApp(); const [showConfirmation, setShowConfirmation] = useState(false); const [reminderNotice, setReminderNotice] = useState('')
  if (!event) return <div className="page"><h1 className="text-2xl font-bold">Event not found</h1><Link to="/" className="mt-4 inline-block text-brand">Back to Explore</Link></div>
  const registered = registeredIds.includes(event.id); const reminder = reminders.find((item) => item.eventId === event.id)
  const eventStarted = new Date(event.startTime).getTime() <= Date.now()
  const updateReminder = () => {
    const changed = toggleReminder(event.id)
    setReminderNotice(changed ? '' : 'This event has already started, so a new reminder cannot be added.')
  }
  return <div className="page max-w-4xl"><Link to="/search" className="text-sm font-bold text-brand">← Back to discover</Link><div className="card mt-5 overflow-hidden"><img src={event.imageUrl} alt="" className="h-64 w-full object-cover sm:h-80" /><div className="p-6 sm:p-8"><div className="flex flex-wrap items-center gap-3"><span className="rounded-full bg-violet-100 px-3 py-1 text-sm font-bold capitalize text-violet-700">{event.category}</span><span className="text-sm text-slate-500">Hosted by {event.organizer}</span></div><h1 className="mt-4 break-words text-3xl font-black tracking-tight sm:text-4xl">{event.title}</h1><p className="mt-5 max-w-2xl break-words text-lg leading-relaxed text-slate-600">{event.description}</p><div className="my-7 grid gap-4 rounded-2xl bg-slate-50 p-5 sm:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-widest text-slate-400">When</p><p className="mt-1 font-bold">{formatDateTime(event.startTime)}</p><p className="text-sm text-slate-500">Until {new Intl.DateTimeFormat('en', { hour: 'numeric', minute: '2-digit' }).format(new Date(event.endTime))}</p></div><div><p className="text-xs font-bold uppercase tracking-widest text-slate-400">Where</p><p className="mt-1 font-bold">{event.location}</p><p className="text-sm text-slate-500">{event.capacity - event.registeredCount} of {event.capacity} places remaining</p></div></div><div className="flex flex-wrap gap-2">{event.tags.map((tag) => <span key={tag} className="rounded-lg bg-slate-100 px-3 py-1.5 text-sm text-slate-600">{tag}</span>)}</div><div className="mt-8 flex flex-wrap gap-3">{registered ? <button className="button-secondary" onClick={() => { unregister(event.id); setReminderNotice('Registration and its reminder were removed.') }}>Unregister from event</button> : <button className="button-primary" disabled={eventStarted} onClick={() => { register(event.id); setShowConfirmation(true) }}>{eventStarted ? 'Event already started' : 'Register for event'}</button>}<button className="button-secondary" onClick={updateReminder}>{reminder?.enabled ? '♧ Reminder added' : eventStarted ? 'Reminder unavailable' : '＋ Add reminder'}</button></div>{reminderNotice && <p className="mt-4 text-sm font-semibold text-slate-500">{reminderNotice}</p>}</div></div>{showConfirmation && <div className="fixed inset-0 z-30 grid place-items-center bg-slate-950/35 p-4"><div className="w-full max-w-sm rounded-3xl bg-white p-7 text-center shadow-2xl"><div className="mx-auto grid size-14 place-items-center rounded-full bg-emerald-100 text-2xl text-emerald-700">✓</div><h2 className="mt-4 text-2xl font-black">You’re registered!</h2><p className="mt-2 text-slate-600">{event.title} is now in your calendar.</p><button onClick={() => setShowConfirmation(false)} className="button-primary mt-6 w-full">Continue exploring</button></div></div>}</div>
}
