import { useMemo, useState } from 'react'
import { EventCard } from '../components/EventCard'
import { allEvents } from '../context/AppContext'
import type { EventCategory } from '../types'

const categories: Array<EventCategory | 'all'> = ['all', 'workshop', 'seminar', 'competition', 'club', 'activity']
export function SearchPage() {
  const [query, setQuery] = useState(''); const [category, setCategory] = useState<EventCategory | 'all'>('all'); const [tag, setTag] = useState(''); const [date, setDate] = useState('')
  const results = useMemo(() => allEvents.filter((event) => { const matchingText = `${event.title} ${event.description} ${event.organizer} ${event.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase()); const matchingTag = !tag || event.tags.some((item) => item.toLowerCase().includes(tag.toLowerCase())); const matchingDate = !date || event.startTime.startsWith(date); return matchingText && matchingTag && matchingDate && (category === 'all' || event.category === category) }), [query, category, tag, date])
  return <div className="page"><p className="eyebrow">Find your fit</p><h1 className="mt-1 text-3xl font-black">Discover events</h1><div className="card mt-6 p-4"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search events, skills, or organisers" className="w-full rounded-xl bg-slate-100 px-4 py-3 outline-none ring-brand focus:ring-2" /><div className="mt-3 grid gap-3 sm:grid-cols-3"><select value={category} onChange={(e) => setCategory(e.target.value as EventCategory | 'all')} className="rounded-xl border border-slate-200 px-3 py-3 capitalize"><option value="all">All categories</option>{categories.slice(1).map((item) => <option key={item}>{item}</option>)}</select><input value={tag} onChange={(e) => setTag(e.target.value)} placeholder="Tag or major (e.g. design)" className="rounded-xl border border-slate-200 px-3 py-3" /><input type="date" value={date} onChange={(e) => setDate(e.target.value)} className="rounded-xl border border-slate-200 px-3 py-3" /></div></div><p className="mt-7 text-sm font-semibold text-slate-500">{results.length} event{results.length === 1 ? '' : 's'} found</p><div className="mt-3 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{results.map((event) => <EventCard key={event.id} event={event} />)}</div>{!results.length && <div className="card mt-4 p-10 text-center text-slate-500"><p className="font-bold text-ink">No {category === 'all' ? '' : `${category} `}events match these filters.</p><p className="mt-2">Try clearing a filter or using a broader keyword.</p></div>}</div>
}
