import { useState } from 'react'
import { useApp } from '../context/AppContext'

const csv = (items: string[]) => items.join(', ')
const parse = (value: string) => value.split(',').map((item) => item.trim()).filter(Boolean)
export function SettingsPage() {
  const { profile, setProfile } = useApp(); const [form, setForm] = useState({ major: profile.major, interests: csv(profile.interests), clubs: csv(profile.clubs), goals: csv(profile.careerGoals) }); const [saved, setSaved] = useState(false)
  const save = () => { setProfile({ ...profile, major: form.major, interests: parse(form.interests), clubs: parse(form.clubs), careerGoals: parse(form.goals) }); setSaved(true); setTimeout(() => setSaved(false), 2200) }
  return <div className="page max-w-3xl"><p className="eyebrow">You control the feed</p><h1 className="mt-1 text-3xl font-black">Your discovery profile</h1><p className="mt-2 text-slate-600">These preferences tune recommendations. Use commas to add more than one item.</p><div className="card mt-7 space-y-5 p-6"><Field label="Your major" value={form.major} onChange={(major) => setForm({ ...form, major })} placeholder="e.g. computer science" /><Field label="Interests" value={form.interests} onChange={(interests) => setForm({ ...form, interests })} placeholder="e.g. ai, design, entrepreneurship" /><Field label="Clubs & societies" value={form.clubs} onChange={(clubs) => setForm({ ...form, clubs })} placeholder="e.g. Data Science Club" /><Field label="Career goals" value={form.goals} onChange={(goals) => setForm({ ...form, goals })} placeholder="e.g. product, technology" /><div className="flex items-center gap-4 pt-2"><button className="button-primary" onClick={save}>Save preferences</button>{saved && <span className="text-sm font-bold text-emerald-600">Saved — your feed is refreshed.</span>}</div></div><div className="mt-5 rounded-2xl border border-indigo-100 bg-indigo-50 p-5 text-sm text-indigo-900"><p className="font-extrabold">How recommendations work</p><p className="mt-1 leading-relaxed">We look for tag matches with your interests, major, clubs, and goals; favour categories you have attended; and lower the score for weekly schedule conflicts.</p></div></div>
}
function Field({ label, value, onChange, placeholder }: { label: string; value: string; onChange: (value: string) => void; placeholder: string }) { return <label className="block"><span className="mb-2 block text-sm font-extrabold">{label}</span><input value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} className="w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-brand focus:ring-2 focus:ring-indigo-100" /></label> }
